### ISSUE TITLE
Webpack gone silence and stall at the last step. 

### ISSUE THREAD

**Issue by Fenici** [coreui/coreui-free-react-admin-template#52] opened 2018-02-02 22:28 UTC
Hi mrholek , 

I am having issues with the run build with the app in react. it's not able to compile 'npm run build' just stuck at last step. 

https://stackoverflow.com/questions/48581536/webpack-npm-run-build-when-stall-or-silence-after-2-hidden-module

C here for more info 

thanks.

**Comment by xidedix** [comment] 2018-04-24 13:04
hi @Fenici 
cannot reproduce - please try the most recent version, it uses create-react-app

**Comment by xidedix** [comment] 2018-06-21 14:07
I'm closing this since the issue is no longer active. Please comment and/or reopen if you feel the issue has not been resolved.

**Closed by xidedix** 2018-06-21 14:07 UTC
