### ISSUE TITLE
How Add new Container Like DefaultLayout in CoreUI ReactJs

### ISSUE THREAD

**Issue by MoradiGit** [coreui/coreui-free-react-admin-template#188] opened 2019-08-06 08:11 UTC
Hi
I have problem to add new Container in my CoreUi React Project
How I can add new Container Like DefaultLayout  for example DefaultappLayout  that have own 
sidebar and specials routes

for example:
```

import React, { Component } from 'react';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import './App.scss';

const loading = () => <div className="animated fadeIn pt-3 text-center">لطفا شکیبا باشید...</div>;

// Containers
const DefaultLayout = React.lazy(() => import('./containers/DefaultLayout'));
const DefaultOutLayout = React.lazy(() => import('./containers/DefaultOutLayout'));

// Pages

const Page404 = React.lazy(() => import('./views/Pages/Page404'));
const Page500 = React.lazy(() => import('./views/Pages/Page500'));

class App extends Component {
  render() {
    return (
      <BrowserRouter>

        <React.Suspense fallback={loading()}>
          <Switch>

            <Route exact path="/404" name="page 404" render={props => <Page404 {...props} />} />
            <Route exact path="/500" name="page 500" render={props => <Page500 {...props} />} />
            <Route exact path="/" name="Home" render={props => <DefaultLayout {...props} />} />
        <Route path="/" name="OutHome" render={props => <DefaultOutLayout {...props} />} />  
          </Switch>
        </React.Suspense>
      </BrowserRouter>
    );
  }
}

export default App;
```

in that App.js of react project I Add 
`<Route path="/" name="OutHome" render={props => <DefaultOutLayout {...props} />} />`

but when I add this I get problem in routing and my 
`<Route path="/" name="Home" render={props => <DefaultLayout {...props} />} />`
doesnt work i just should use onse of top route
How Should I solve my problem???

https://github.com/coreui/coreui-free-react-admin-template/issues/187 full code here!

**Comment by woothu** [comment] 2020-06-25 11:38
Duplicate of #187

**Closed by woothu** 2020-06-25 11:38 UTC
