### ISSUE TITLE
build freezes on "Creating an optimized production build..."

### ISSUE THREAD

**Issue by jmandivarapu1** [coreui/coreui-free-react-admin-template#178] opened 2019-04-26 21:44 UTC
Hi,

I am Using COREUI Pro Version of reactjs but didn't got access to private repo so raising the issues here.

[I am running using SUDO]

When i try to create the build it says "Creating an Optimized Production Build" then stays like that forever. It is effecting my work as my aws amplify run the build command first.

Out of curiosity I tried running the same script in the free version  and result is excatly the same it just gets struck there and nothing happens.

I tried on Mac/Windows/Ubuntu all let to the same result.

Can anybody help me here?

Regards,
Jay

**Comment by xidedix** [comment] 2019-04-27 15:33
duplicate of https://github.com/coreui/coreui-free-react-admin-template/issues/125

**Closed by xidedix** 2019-04-27 15:33 UTC
Labels: duplicate
